name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.sohcah.dev
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          tags: registry.sohcah.dev/megalodon/megalodon:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push to Registry
        run: |
          docker push registry.sohcah.dev/megalodon/megalodon:latest
